app = "your-app-name-here"

[build]
  dockerfile = "Dockerfile"
  [build.secrets]
    FOUNDRY_TOKEN = "secret:FOUNDRY_TOKEN"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
